// TALK 5

IF
    InParty(Myself)
    !StateCheck(Myself,CD_STATE_NOTVALID)
    !StateCheck(Player1,CD_STATE_NOTVALID)
	Global("C0DrakeTalk","GLOBAL",9)
	RealGlobalTimerExpired("C0SireneLovetalkTimer","GLOBAL")
	TimeOfDay(NIGHT)
	AreaType("OUTDOOR")
THEN
  RESPONSE #100
    SetGlobal("C0DrakeTalk","GLOBAL",10)
END

IF
	InParty(Myself)
	Global("C0DrakeTalk","GLOBAL",10)
THEN
  RESPONSE #100
	StartDialogueNoSet(Player1)
END